version: '3'
services:
  # prom:
  #   image: pratham17/prom:v7
  #   networks:
  #     my_network:
  #       ipv4_address: 172.18.0.2
  #   ports:
  #     - "9090:9090"  # Map container port 9090 to host port 9090

  # graf:
  #   image: pratham17/graf:v2
  #   networks:
  #     my_network:
  #       ipv4_address: 172.18.0.3
  #   ports:
  #     - "3000:3000"  # Map container port 3000 to host port 3000

  jenk:
    image: pratham17/jenkins:v7
    ports:
      - "8084:8080"
    container_name: jenk-host
    networks:
      my_network:
        ipv4_address: 172.18.0.4
    entrypoint: /entrypoint.sh

  dock:
    image: pratham17/dock:v4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    networks:
      my_network:
        ipv4_address: 172.18.0.5
    container_name: dock-host
    privileged: true
    entrypoint: /entrypoint.sh
    # command: ["dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375"]

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
